// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/tinygodsdev/orrery/internal/repository/entgo/ent/predicate"
	"github.com/tinygodsdev/orrery/internal/repository/entgo/ent/test"
	"github.com/tinygodsdev/orrery/internal/repository/entgo/ent/testdisplay"
)

// TestDisplayQuery is the builder for querying TestDisplay entities.
type TestDisplayQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.TestDisplay
	// eager-loading edges.
	withTest *TestQuery
	withFKs  bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TestDisplayQuery builder.
func (tdq *TestDisplayQuery) Where(ps ...predicate.TestDisplay) *TestDisplayQuery {
	tdq.predicates = append(tdq.predicates, ps...)
	return tdq
}

// Limit adds a limit step to the query.
func (tdq *TestDisplayQuery) Limit(limit int) *TestDisplayQuery {
	tdq.limit = &limit
	return tdq
}

// Offset adds an offset step to the query.
func (tdq *TestDisplayQuery) Offset(offset int) *TestDisplayQuery {
	tdq.offset = &offset
	return tdq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (tdq *TestDisplayQuery) Unique(unique bool) *TestDisplayQuery {
	tdq.unique = &unique
	return tdq
}

// Order adds an order step to the query.
func (tdq *TestDisplayQuery) Order(o ...OrderFunc) *TestDisplayQuery {
	tdq.order = append(tdq.order, o...)
	return tdq
}

// QueryTest chains the current query on the "test" edge.
func (tdq *TestDisplayQuery) QueryTest() *TestQuery {
	query := &TestQuery{config: tdq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := tdq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := tdq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(testdisplay.Table, testdisplay.FieldID, selector),
			sqlgraph.To(test.Table, test.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, testdisplay.TestTable, testdisplay.TestColumn),
		)
		fromU = sqlgraph.SetNeighbors(tdq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first TestDisplay entity from the query.
// Returns a *NotFoundError when no TestDisplay was found.
func (tdq *TestDisplayQuery) First(ctx context.Context) (*TestDisplay, error) {
	nodes, err := tdq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{testdisplay.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (tdq *TestDisplayQuery) FirstX(ctx context.Context) *TestDisplay {
	node, err := tdq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first TestDisplay ID from the query.
// Returns a *NotFoundError when no TestDisplay ID was found.
func (tdq *TestDisplayQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = tdq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{testdisplay.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (tdq *TestDisplayQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := tdq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single TestDisplay entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one TestDisplay entity is found.
// Returns a *NotFoundError when no TestDisplay entities are found.
func (tdq *TestDisplayQuery) Only(ctx context.Context) (*TestDisplay, error) {
	nodes, err := tdq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{testdisplay.Label}
	default:
		return nil, &NotSingularError{testdisplay.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (tdq *TestDisplayQuery) OnlyX(ctx context.Context) *TestDisplay {
	node, err := tdq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only TestDisplay ID in the query.
// Returns a *NotSingularError when more than one TestDisplay ID is found.
// Returns a *NotFoundError when no entities are found.
func (tdq *TestDisplayQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = tdq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{testdisplay.Label}
	default:
		err = &NotSingularError{testdisplay.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (tdq *TestDisplayQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := tdq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of TestDisplays.
func (tdq *TestDisplayQuery) All(ctx context.Context) ([]*TestDisplay, error) {
	if err := tdq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return tdq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (tdq *TestDisplayQuery) AllX(ctx context.Context) []*TestDisplay {
	nodes, err := tdq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of TestDisplay IDs.
func (tdq *TestDisplayQuery) IDs(ctx context.Context) ([]uuid.UUID, error) {
	var ids []uuid.UUID
	if err := tdq.Select(testdisplay.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (tdq *TestDisplayQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := tdq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (tdq *TestDisplayQuery) Count(ctx context.Context) (int, error) {
	if err := tdq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return tdq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (tdq *TestDisplayQuery) CountX(ctx context.Context) int {
	count, err := tdq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (tdq *TestDisplayQuery) Exist(ctx context.Context) (bool, error) {
	if err := tdq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return tdq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (tdq *TestDisplayQuery) ExistX(ctx context.Context) bool {
	exist, err := tdq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TestDisplayQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (tdq *TestDisplayQuery) Clone() *TestDisplayQuery {
	if tdq == nil {
		return nil
	}
	return &TestDisplayQuery{
		config:     tdq.config,
		limit:      tdq.limit,
		offset:     tdq.offset,
		order:      append([]OrderFunc{}, tdq.order...),
		predicates: append([]predicate.TestDisplay{}, tdq.predicates...),
		withTest:   tdq.withTest.Clone(),
		// clone intermediate query.
		sql:    tdq.sql.Clone(),
		path:   tdq.path,
		unique: tdq.unique,
	}
}

// WithTest tells the query-builder to eager-load the nodes that are connected to
// the "test" edge. The optional arguments are used to configure the query builder of the edge.
func (tdq *TestDisplayQuery) WithTest(opts ...func(*TestQuery)) *TestDisplayQuery {
	query := &TestQuery{config: tdq.config}
	for _, opt := range opts {
		opt(query)
	}
	tdq.withTest = query
	return tdq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		RandomizeOrder bool `json:"randomize_order,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.TestDisplay.Query().
//		GroupBy(testdisplay.FieldRandomizeOrder).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (tdq *TestDisplayQuery) GroupBy(field string, fields ...string) *TestDisplayGroupBy {
	grbuild := &TestDisplayGroupBy{config: tdq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := tdq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return tdq.sqlQuery(ctx), nil
	}
	grbuild.label = testdisplay.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		RandomizeOrder bool `json:"randomize_order,omitempty"`
//	}
//
//	client.TestDisplay.Query().
//		Select(testdisplay.FieldRandomizeOrder).
//		Scan(ctx, &v)
//
func (tdq *TestDisplayQuery) Select(fields ...string) *TestDisplaySelect {
	tdq.fields = append(tdq.fields, fields...)
	selbuild := &TestDisplaySelect{TestDisplayQuery: tdq}
	selbuild.label = testdisplay.Label
	selbuild.flds, selbuild.scan = &tdq.fields, selbuild.Scan
	return selbuild
}

func (tdq *TestDisplayQuery) prepareQuery(ctx context.Context) error {
	for _, f := range tdq.fields {
		if !testdisplay.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if tdq.path != nil {
		prev, err := tdq.path(ctx)
		if err != nil {
			return err
		}
		tdq.sql = prev
	}
	return nil
}

func (tdq *TestDisplayQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*TestDisplay, error) {
	var (
		nodes       = []*TestDisplay{}
		withFKs     = tdq.withFKs
		_spec       = tdq.querySpec()
		loadedTypes = [1]bool{
			tdq.withTest != nil,
		}
	)
	if tdq.withTest != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, testdisplay.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		return (*TestDisplay).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		node := &TestDisplay{config: tdq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, tdq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}

	if query := tdq.withTest; query != nil {
		ids := make([]uuid.UUID, 0, len(nodes))
		nodeids := make(map[uuid.UUID][]*TestDisplay)
		for i := range nodes {
			if nodes[i].test_display == nil {
				continue
			}
			fk := *nodes[i].test_display
			if _, ok := nodeids[fk]; !ok {
				ids = append(ids, fk)
			}
			nodeids[fk] = append(nodeids[fk], nodes[i])
		}
		query.Where(test.IDIn(ids...))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			nodes, ok := nodeids[n.ID]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "test_display" returned %v`, n.ID)
			}
			for i := range nodes {
				nodes[i].Edges.Test = n
			}
		}
	}

	return nodes, nil
}

func (tdq *TestDisplayQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := tdq.querySpec()
	_spec.Node.Columns = tdq.fields
	if len(tdq.fields) > 0 {
		_spec.Unique = tdq.unique != nil && *tdq.unique
	}
	return sqlgraph.CountNodes(ctx, tdq.driver, _spec)
}

func (tdq *TestDisplayQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := tdq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (tdq *TestDisplayQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   testdisplay.Table,
			Columns: testdisplay.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: testdisplay.FieldID,
			},
		},
		From:   tdq.sql,
		Unique: true,
	}
	if unique := tdq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := tdq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, testdisplay.FieldID)
		for i := range fields {
			if fields[i] != testdisplay.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := tdq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := tdq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := tdq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := tdq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (tdq *TestDisplayQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(tdq.driver.Dialect())
	t1 := builder.Table(testdisplay.Table)
	columns := tdq.fields
	if len(columns) == 0 {
		columns = testdisplay.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if tdq.sql != nil {
		selector = tdq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if tdq.unique != nil && *tdq.unique {
		selector.Distinct()
	}
	for _, p := range tdq.predicates {
		p(selector)
	}
	for _, p := range tdq.order {
		p(selector)
	}
	if offset := tdq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := tdq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// TestDisplayGroupBy is the group-by builder for TestDisplay entities.
type TestDisplayGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (tdgb *TestDisplayGroupBy) Aggregate(fns ...AggregateFunc) *TestDisplayGroupBy {
	tdgb.fns = append(tdgb.fns, fns...)
	return tdgb
}

// Scan applies the group-by query and scans the result into the given value.
func (tdgb *TestDisplayGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := tdgb.path(ctx)
	if err != nil {
		return err
	}
	tdgb.sql = query
	return tdgb.sqlScan(ctx, v)
}

func (tdgb *TestDisplayGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range tdgb.fields {
		if !testdisplay.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := tdgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tdgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (tdgb *TestDisplayGroupBy) sqlQuery() *sql.Selector {
	selector := tdgb.sql.Select()
	aggregation := make([]string, 0, len(tdgb.fns))
	for _, fn := range tdgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(tdgb.fields)+len(tdgb.fns))
		for _, f := range tdgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(tdgb.fields...)...)
}

// TestDisplaySelect is the builder for selecting fields of TestDisplay entities.
type TestDisplaySelect struct {
	*TestDisplayQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (tds *TestDisplaySelect) Scan(ctx context.Context, v interface{}) error {
	if err := tds.prepareQuery(ctx); err != nil {
		return err
	}
	tds.sql = tds.TestDisplayQuery.sqlQuery(ctx)
	return tds.sqlScan(ctx, v)
}

func (tds *TestDisplaySelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := tds.sql.Query()
	if err := tds.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
